# fly.toml app configuration file generated for gimme-app on 2024-10-25T08:54:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gimme-app'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
